### ISSUE TITLE
Categorías

### ISSUE THREAD

**Issue by lmorillas** [mariaestmag/tutorial_wagtail#3]
https://github.com/mariaestmag/tutorial_wagtail/blob/354f4565edde98e8f172d1fba39d8a00cd008b9c/blog/models.py#L71  Esta información es redundante y se debería de eliminar manteniendo la funcionalidad: seleccionar por tipos de páginas de blog

**Comment by mariaestmag** [comment]
Para evitar la redundancia pensé en decirle a cada tipo de página qué categoría utilizar y así evito tocar todo el código:

```
class BlogPage(Page):
   ...
    tags = ClusterTaggableManager(through=BlogPageTag, blank=True)
    categories = ParentalManyToManyField('blog.BlogCategory', blank=True)
    choice = BlogCategory.objects.filter(name='Genérica')


   content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('categories', widget=forms.Select(choice)),
```

pero parece que no funciona y por más documentación que busco no doy con la tecla.
